name: Automatic tests for net-paranoid

on:
  - push
  - pull_request

jobs:
  testing:
    name: Testing net-paranoid
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.13'
      - run: go test -v ./...
